version: "3.9"
services:
  my-node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-graphql
    ports:
      - 4000:4000
    command: npm start
    volumes:
      - .:/usr/src/app/
    restart: always